<?php         
$this->title = "My Album";
$this->headTitle($this->title);
?>

<p><a href="<?php echo $this->url(array('controller'=>'customer', 
        'action'=>'customerssearch'));?>">Searching Customers...</a></p>

<p><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'add'));?>">Add new album</a></p>
<table>
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->albums as $album) : ?>
<tr>
    <td><?php echo $this->escape($album->vorname);?></td>
    <td><?php echo $this->escape($album->nachname);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'edit', 'id'=>$album->id));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'delete', 'id'=>$album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>